### PR TITLE
Update package for Bioc 3.9

### PR DESCRIPTION
**Pull request by DarwinAwardWinner**
These commits allow the package to build and pass tests with BiocParallel 1.18.0 (Bioconductor 3.9). The first commit no longer passes `catch.errors`to the constructor. I guess this argument was previously deprecated and is now removed. I've taken the conservative approach of leaving the argument in `FutureParam` but simply not passing it along. That is, `FutureParam` will still accept this argument but it will have no effect. Of course, you can simply remove it altogether instead.

The second commit switches to using BiocParallel's prototype-based system for constructing argument lists that will be past to param constructors. This fixes errors relating to missing arguments.

With these two commits, `R CMD check` passes on my system with no errors, warnings, or notes.

### CODE REVIEW

**Comment by DarwinAwardWinner** [comment]
Oh, and this fixes #2, of course.

**Comment by HenrikBengtsson** [comment]
Thanks for this. I'm at useR2019 and traveling for these next two weeks so won't have much time to look at this. A quick question:

Q. How far back in Bioc versions are these changes compatible with? Will they work with Bioc 3.8? 3.7?

If not, we might want to make these updates conditionally on the Bioc/BiocParallel version.

**Comment by DarwinAwardWinner** [comment]
I have no idea how backward-compatible this is. I haven't been tracking the recent development in BiocParallel, so I don't know exactly when these changes happened.

**Comment by DarwinAwardWinner** [comment]
Looking at the other branches, I don't see this prototype system in Bioc 3.7, and there is no branch for 3.8. This looks like the commit where it was implemented: https://github.com/Bioconductor/BiocParallel/commit/7d75ffc21bc8c3190691d055d6c26b858f12c1e0. It seems to be a workaround for the refclass initializer method being broken.

**Comment by DarwinAwardWinner** [comment]
As for supporting multiple BiocParallel versions, the obvious method is to have multiple branches of this package. I'm not sure if there's a way to import a variable from another package that may or may not exist depending on the version of that package, so supporting all versions might be impossible.

**Comment by HenrikBengtsson** [comment]
Merged.  Now available in BiocParallel.FutureParam 0.2.0.  Thanks again for this.

FYI, I've updated the code such that it works with older versions of Bioconductor as well.

**Pull request merged**
